# cloudbuild.yaml

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=hospital-cluster'

steps:
  #1️⃣ Build de l’image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hospital-app'
      - '.'

  # 2️⃣ Récupération des credentials du cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials "$CLOUDSDK_CONTAINER_CLUSTER" \
          --zone "$CLOUDSDK_COMPUTE_ZONE" \
          --project "$PROJECT_ID"

  # 3️⃣ Déploiement sur GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './k8s/deployment.yaml'

# Pousser l’image dans GCR
images:
  - 'gcr.io/$PROJECT_ID/hospital-app'


