# cloudbuild.yaml

steps:
  #1️⃣ Build de l’image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hospital-app'
      - '.'

  # 2️⃣ Récupérer les credentials Kubernetes
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials hospital-cluster \
          --zone=europe-west1-b \
          --project=$PROJECT_ID

  # 3️⃣ Déployer sur GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './k8s/deployment.yaml'

# Pousser l’image dans GCR
images:
  - 'gcr.io/$PROJECT_ID/hospital-app'

options:
  logging: CLOUD_LOGGING_ONLY



