steps:
  #1️⃣ Build de l’image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hospital-app'
      - '.'

  # 2️⃣ Récupérer les credentials et déployer dans la foulée
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Récupérer les creds Kubernetes
        gcloud container clusters get-credentials hospital-cluster \
          --zone=europe-west1-b \
          --project=$PROJECT_ID

        # Déployer le manifeste
        kubectl apply -f ./k8s/deployment.yaml

# Pousser l’image dans GCR
images:
  - 'gcr.io/$PROJECT_ID/hospital-app'

options:
  logging: CLOUD_LOGGING_ONLY




